server:
  port: 8001

spring:
  application:
    name: spring-redis
  redis:
    host: localhost
    port: 6379
    timeout: 10000
  cache:
    type: REDIS
    redis:
      cache-null-values: false
      use-key-prefix: true
      key-prefix: springRedis
      time-to-live: 60000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/spring-redis?useSSL=false
    username: root
    password: T0kh@66053
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE